defaults: &defaults
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: bragi_development

test:
  <<: *defaults
  database: bragi_test

# set these environment variables on your prod server
production:
  uri: <%= ENV["MONGO_URI"] %>
